path: ../datasets # dataset root dir
train: images/train # train images (relative to 'path')
val: images/valid # val images (relative to 'path')

# Classes
nc : 14 # number of classes
# names: ["angle", 'bottle', 'calculator', 'card', 'earbud', 'gear', 'ipad','key','phone', 'star', 'stationery', 'triangle', 'wallet','watch'] # class names

names: {
  0: "angle",
  1: "bottle",
  2: "calculator",
  3: "card",
  4: "earbud",
  5: "gear",
  6: "ipad",
  7: "key",
  8: "phone",
  9: "star",
  10: "stationery",
  11: "triangle",
  12: "wallet",
  13: "watch"
}
