path: ../data # dataset root dir
train: images/train # train images (relative to 'path')
val: images/valid # val images (relative to 'path')
test: images/test

# Classes
nc : 14 # number of classes
names: ["angle", 'bottle', 'calculator', 'card', 'earbud', 'gear', 'ipad','key','phone', 'star', 'stationery', 'triangle', 'wallet','watch'] # class names