path: ../datasets # dataset root dir
train: dataset/dataset_5_Fold_Cross_val/split_4/train # train images (relative to 'path')
val: dataset/dataset_5_Fold_Cross_val/split_4/val  # val images (relative to 'path')

# Classes
nc : 10 # number of classes

names: {
  0: "angle",
  1: "circle",
  2: "cylinder",
  3: "gear",
  4: "oval",
  5: "rectangle",
  6: "spiky",
  7: "square",
  8: "star",
  9: "triangle",
}
